name: Publish

on:
  workflow_run:
    workflows: [Test]
    # branches: [main]
    types:  [completed]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - run: echo "I am running"
      # - uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      #
      # - name: Python Semantic Release
      #   uses: relekang/python-semantic-release@master
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     pypi_token: ${{ secrets.PYPI_TOKEN }}
